### PR TITLE
integrate with voyager server

### PR DESCRIPTION
**Pull request by wtrocki**
It works when using linked version. When using released version it seems that we are missing some files

screen shot 2018-12-18 at 11 23 30 am

### CODE REVIEW

**Comment by danielpassos** [comment]
```
/Users/passos/.nvm/versions/node/v8.12.0/bin/node /Users/passos/.nvm/versions/node/v8.12.0/lib/node_modules/npm/bin/npm-cli.js run start --scripts-prepend-node-path=auto

> server-apollo@1.0.0 start /Users/passos/Development/Projects/AeroGear/apollo-voyager-ionic-example/server
> nodemon src/index.js

[nodemon] 1.18.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node src/index.js`
module.js:550
    throw err;
    ^

Error: Cannot find module './config/DefaultVoyagerConfig'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/passos/Development/Projects/AeroGear/apollo-voyager-ionic-example/node_modules/@aerogear/apollo-voyager-server/dist/apollo-voyager-server.js:7:32)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by wtrocki** [comment]
Yes. We waiting for another release as package was broken.

**Comment by wtrocki** [comment]
After update it fails on
```
Error: Cannot find module './ApolloVoyagerServer'
    at Function.Module._resolveFilename (module.js:547:15)
```

**Comment by danielpassos** [comment]
Going to rebase and merge

**Pull request merged**
