### PR TITLE
JS-SDK integration

### PR DESCRIPTION
**Pull request by wtrocki**
Replace Apollo Client by AeroGear Sync

## Verification steps:
Please follow the README for running the project. 
Check basing functionalities.
Check window.localstorage for offline queue.

More advanced tests will be performed in separate task.

### CODE REVIEW

**Comment by danielpassos** [comment]
Hey @darahayes @StephenCoady @wtrocki, I need a hand here on JS.

I'm creating a new ApolloClient using [our SDK](https://github.com/aerogear/aerogear-js-sdk/blob/master/packages/sync/src/createClient.ts#L15). I'm doing that in an async/await method [`createApolloClient`](https://github.com/aerogear/apollo-voyager-ionic-example/pull/1/files#diff-4dd6f1595c4e008a7a556ab955fbee71R22) but for some reason it still a promise and when I fire any method I got `ERROR TypeError: this.apollo.query is not a function`

I have no idea how to fix it. Any help is welcome.

**Comment by wtrocki** [comment]
Exact problem with solution: 
https://stackoverflow.com/questions/46257184/angular-async-factory-provider

**Comment by danielpassos** [comment]
@wtrocki Thanks for the link. I have fixed that problem using the `provide: APP_INITIALIZER` trick.

PS: I did a force push!

**Comment by danielpassos** [comment]
This PR makes me things about: 

1. For some reason after adding the `"@aerogear/datasync-js": "0.0.1-alpha",` I started to have a problem with Jasmine dependency and need to remove it.

```
/Users/passos/.nvm/versions/node/v8.12.0/bin/node /Users/passos/.nvm/versions/node/v8.12.0/lib/node_modules/npm/bin/npm-cli.js run start --scripts-prepend-node-path=auto

> ionic4-starter-app@0.0.1 start /Users/passos/Development/Projects/AeroGear/ionic4-grapqhl-starter
> ionic serve

> ng run app:serve --host=0.0.0.0 --port=8100

[INFO] Development server running!
       
       Local: http://localhost:8100
       External: http://192.168.1.8:8100
       DevApp: ionic4-starter-app@8100 on Passos-MacBook-Pro
       
       Use Ctrl+C to quit this process

[INFO] Browser window opened to http://localhost:8100!

[ng] ℹ ｢wdm｣: wait until bundle finished: /
[ng] Date: 2018-12-06T23:11:33.731Z
[ng] Hash: 1f695c77549af6a04533
[ng] Time: 7325ms
[ng] chunk {main} main.js, main.js.map (main) 1.99 kB [initial] [rendered]
[ng] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 712 bytes [initial] [rendered]
[ng] chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
[ng] chunk {styles} styles.js, styles.js.map (styles) 36.1 kB [initial] [rendered]
[ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 326 kB [initial] [rendered]
[ng] ERROR in node_modules/@types/jasmine/index.d.ts(14,18): error TS2300: Duplicate identifier 'describe'.
[ng] node_modules/@types/jasmine/index.d.ts(16,18): error TS2300: Duplicate identifier 'xdescribe'.
[ng] node_modules/@types/jasmine/index.d.ts(25,18): error TS2300: Duplicate identifier 'it'.
[ng] node_modules/@types/jasmine/index.d.ts(35,18): error TS2300: Duplicate identifier 'xit'.
[ng] node_modules/@types/jasmine/index.d.ts(50,18): error TS2300: Duplicate identifier 'beforeEach'.
[ng] node_modules/@types/jasmine/index.d.ts(57,18): error TS2300: Duplicate identifier 'afterEach'.
[ng] node_modules/@types/jasminewd2/index.d.ts(9,18): error TS2300: Duplicate identifier 'it'.
[ng] node_modules/@types/jasminewd2/index.d.ts(11,18): error TS2300: Duplicate identifier 'xit'.
[ng] node_modules/@types/jasminewd2/index.d.ts(12,18): error TS2300: Duplicate identifier 'beforeEach'.
[ng] node_modules/@types/jasminewd2/index.d.ts(13,18): error TS2300: Duplicate identifier 'afterEach'.
[ng] node_modules/@types/mocha/index.d.ts(2680,13): error TS2300: Duplicate identifier 'beforeEach'.
[ng] node_modules/@types/mocha/index.d.ts(2698,13): error TS2300: Duplicate identifier 'afterEach'.
[ng] node_modules/@types/mocha/index.d.ts(2714,13): error TS2300: Duplicate identifier 'describe'.
[ng] node_modules/@types/mocha/index.d.ts(2735,13): error TS2300: Duplicate identifier 'xdescribe'.
[ng] node_modules/@types/mocha/index.d.ts(2749,13): error TS2300: Duplicate identifier 'it'.
[ng] node_modules/@types/mocha/index.d.ts(2770,13): error TS2300: Duplicate identifier 'xit'.
[ng] ℹ ｢wdm｣: Failed to compile.

```

2. Using our Sync SDK I needed to add the apollo dependency `"apollo-client": "^2.4.0",` only to be able to have a `ApolloClient` variable. 

```
let apollo: ApolloClient = ...
```

Should we export it on AeroGear Sync SDK to people don't need to include it?

3. The `ApolloClient` we are [providing on AeroGear Android SDK](https://github.com/aerogear/aerogear-js-sdk/blob/master/packages/sync/src/createClient.ts#L19) is a `ApolloClient<NormalizedCacheObject>` but it comes from [_apollo-cache-inmemory_](https://github.com/apollographql/apollo-client/tree/master/packages/apollo-cache-inmemory) so what kind of type the developer should use when using TypeScript?

**Comment by StephenCoady** [comment]
@danielpassos I'm not sure about point 1. But wrt point 2 I would have thought that if the sdk uses a module then it is added in a flat structure anyway so everything above that has access, is apollo client not available in the apps node modules?

For point 3 I will have to get back to you, I think I may have been the one who changed it to NormalizedCacheObject but off the top of my head I can't remember why. I'll check and come back to you.

**Comment by wtrocki** [comment]
1. Jasmine clashes with mocha types
https://github.com/angular/protractor/issues/3880

However our package should not expose mocha types. 
So this is an error we should fix possibly by excluding mocha completely from production build (not sure how types landed into this anyway)

**Comment by wtrocki** [comment]
2. Problem can be resolved by adding explicitly Apollo client to return object of `createClient` 
Then exposing this type will happen automatically by compiler. Doing that now

**Comment by wtrocki** [comment]
3. Is going to be resolved by resolving point 2.

**Comment by wtrocki** [comment]
All done in: https://github.com/aerogear/aerogear-js-sdk/pull/181
Going to release new build after

**Comment by wtrocki** [comment]
npm publish
+ @aerogear/datasync-js@0.0.2-alpha

**Comment by ziccardi** [comment]
👀

**Comment by wtrocki** [comment]
OK. So  I guess we are ready to start testing end to end implementation.

@darahayes @StephenCoady @danielpassos This is kinda critical for us to finalize work on offline mutation/query. Every possible input helps.

**Comment by darahayes** [comment]
Hey folks, sorry about coming to this so late. Going to try review and verify this now.

**Comment by danielpassos** [comment]
@wtrocki  Hi-5

**Pull request merged**
